### ISSUE TITLE
Water bucket crash

### ISSUE THREAD

**Issue by ryanj1792** [TeamAOF/All-of-Fabric-4#131] opened 2021-11-02 09:39 UTC
for some reason every so often getting water in a bucket crashes my game

crash report maybe related to the dank mod?

Time: 11/2/21, 9:35 AM
Description: Unexpected error

java.lang.RuntimeException: Attempted to get inventory on client
	at tfar.dankstorage.utils.Utils.getInventory(Utils.java:234)
	at tfar.dankstorage.event.MixinHooks.onItemPickup(MixinHooks.java:43)
	at tfar.dankstorage.event.MixinHooks.interceptItem(MixinHooks.java:32)
	at net.minecraft.class_1661.handler$bdc000$interceptItems(class_1661.java:3187)
	at net.minecraft.class_1661.method_7394(class_1661.java)
	at net.minecraft.class_5328.method_30270(class_5328.java:43)
	at net.minecraft.class_5328.method_30012(class_5328.java:50)
	at net.minecraft.class_1755.method_7836(class_1755.java:68)
	at net.minecraft.class_1799.method_7913(class_1799.java:254)
	at net.minecraft.class_636.method_2919(class_636.java:361)
	at net.minecraft.class_310.method_1583(class_310.java:1666)
	at net.minecraft.class_310.method_1508(class_310.java:1900)
	at net.minecraft.class_310.method_1574(class_310.java:1728)
	at net.minecraft.class_310.method_1523(class_310.java:1081)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

**Comment by AndaleTheGreat1** [comment] 2021-11-03 20:13
you should post your logs thru pastebin.com otherwise it cuts off. 
are you carrying a dank?
is it a stack of buckets?
if so then https://github.com/TeamAOF/All-of-Fabric-4/issues/125

**Comment by Monster-Zer0** [comment] 2021-11-05 15:35
duplicate of #125 which has been reported to mod author already. we will keep #125 open to track the issue, while closing this one.

**Closed by Monster-Zer0** 2021-11-05 15:35 UTC
Labels: duplicate, mod issue
