### ISSUE TITLE
Random CtD, crash log uploaded

### ISSUE THREAD

**Issue by darkedone02** [TeamAOF/All-of-Fabric-4#123] opened 2021-10-28 12:20 UTC
https://paste.ee/p/IGVnX

This crash was random, just started building a house out of planks.

**Comment by Monster-Zer0** [comment] 2021-11-05 15:14
duplicate of

https://github.com/TeamAOF/All-of-Fabric-4/issues/117

**Closed by Monster-Zer0** 2021-11-05 15:14 UTC
Labels: duplicate, mod issue
